<a href="https://colab.research.google.com/github/SubhamMohanty187/Data-Science/blob/main/Extract_Data_using_API_%26_WebScraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

## Using API

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=90de64ccd37cdb5f60e7b03015b62dae&language=en-US&page=1') # Use API key and run

In [ ]:
response.json()['results'][0:4]

[{'adult': False,
  'backdrop_path': '/avedvodAZUcwqevBfm8p4G2NziQ.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 188.643,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.706,
  'vote_count': 26527},
 {'adult': False,
  'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 204.998,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.692,
  'vote_count': 20139},
 {'adult': False,
  'backdrop_path': '/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 167.068,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.576,
  'vote_count': 12150},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 136.269,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.566,
  'vote_count': 15558}]

Since this is in a dict format, we can convert it to a dataframe to use it for easier computation and select the required columns

In [ ]:
temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,188.643,8.706,26527
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,204.998,8.692,20139
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,167.068,8.576,12150
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,136.269,8.566,15558
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,94.056,8.544,8402
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-04-18,151.280,8.537,16165
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,79.180,8.536,4410
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,168.441,8.516,32281
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,148.168,8.509,17816
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,125.244,8.506,17042
10,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,180.841,8.488,11138
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,138.913,8.500,27426
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-01,195.583,8.482,23687
13,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.941,8.476,26933
14,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,161.982,8.500,12579
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,111.983,8.500,8397
16,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,71.793,8.500,3567
17,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,30.024,8.458,380
18,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.083,8.458,5338
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,81.862,8.451,12832

### The above code is working fine but it is for page 1 out of 428 pages. So we need to extract all the pages from the api by adding the request in a for loop.

In [ ]:
final_df = pd.DataFrame()  # Create an empty dataframe to store the data
for i in range(1,429):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=90de64ccd37cdb5f60e7b03015b62dae&language=en-US&page={pagenum}'.format(pagenum=i))
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  final_df = final_df._append(temp_df,ignore_index=True)

In [ ]:
final_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,188.643,8.706,26527
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,204.998,8.692,20139
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,167.068,8.576,12150
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,136.269,8.566,15558
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,94.056,8.544,8402
...,...,...,...,...,...,...,...
8555,441384,The Beach Bum,An irreverent comedy about the misadventures o...,2019-03-21,24.414,5.650,484
8556,2800,Rumor Has It...,Sarah Huttinger's return home with her fiance ...,2005-12-22,25.885,5.650,1120
8557,146238,Runner Runner,When a poor college student who cracks an onli...,2013-09-24,40.498,5.649,1211
8558,9381,Babylon A.D.,A veteran-turned-mercenary is hired to take a ...,2008-08-20,75.596,5.649,2046
8559,39451,Little Fockers,"It has taken 10 years, two little Fockers with...",2010-12-21,37.617,5.648,3156

In [ ]:
final_df.shape

(8560, 7)

In [ ]:
final_df.iloc[0:2,:] # iloc[rows, cols]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,188.643,8.706,26527
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,204.998,8.692,20139

## WebScraping using BeautifulSoup

Ref-: https://github.com/campusx-official/100-days-of-machine-learning/blob/main/day18-pandas-dataframe-using-web-scraping/day18.ipynb

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

### if response code is 403

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} -requests.get('url',headers=headers).text

Since some websites don't allow to external API to access their web data, so we need to add the above header to mask the request. Here, we will use ambitionbox website to fetch thei company info data.

In [ ]:
requests.get('https://www.ambitionbox.com/list-of-companies?page=1').text

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;9a4cb17&#46;1722362417&#46;bab4a3\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;9a4cb17&#46;1722362417&#46;bab4a3</P>\n</BODY>\n</HTML>\n'

This above error we get if we don't add the header.

In [ ]:
head={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

In [ ]:
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=head)

In [ ]:
soup = BeautifulSoup(webpage.text,'lxml')